#!/bin/bash
#options=( 'Install Apps vi apt-get' 'Copy Dotfile To The System' 'Backup dotfile From The System' 'Create Favorite Directory' 'Quit')
#yoni=(1 2 3)
#
DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P $DIR && pwd)


options=(
    'Install System Application(Main PC, Not for VM)'
    'Install Programming Languages enviroment'
    'Install Terminal Based Application'
    'Install Gui Based Application'
    'Quit')

print_menu(){
	NORMAL=`echo "\033[m"`
	MENU=`echo "\e[97m"` #White
	NUMBER=`echo "\e[93m"` #Light Yellow
	FGRED=`echo "\033[41m"`
	RED_TEXT=`echo "\033[31m"`
	ENTER_LINE=`echo "\033[33m"`
	echo -e "${MENU}*********************************************${NORMAL}"
	for ((i=1;i<${#options[@]}+1;i++))
	do
		echo -e "${MENU}${NUMBER} ${i})${MENU} ${options[$i-1]}"
	done
	echo -e "${MENU}*********************************************${NORMAL}"
	echo -e "${ENTER_LINE}Please enter a menu option and enter or ${RED_TEXT}enter to exit. ${NORMAL}"
	read opt
}
print_menu

if [ ${opt} -eq ${#options[@]} ]
then
    echo "exit"
else
	case $opt in
	1)
        echo "Installing System Application"
        bash "${DIR}"/install_scripts/01system_install.sh
	;;
    2)
        echo "Installing Programming Languages"
        bash "${DIR}"/install_scripts/02programming-lang-install.sh
	;;
    3)
        echo "Installing Terminal Based Application"
        bash "${DIR}"/install_scripts/03terminal_apps_install.sh
	;;
    4)
        echo "Installing Gui Based Application"
        bash "${DIR}"/install_scripts/04gui_apps_install.sh
    ;;
	esac
fi
