#!/usr/bin/env bash
#
DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P "$DIR" && pwd)

source "${DIR}"/../../utils/package/github

function _create_config()
{
    local config_dir="${HOME}/.config/ripgrep"
    local config_file="${config_dir}/ripgreprc"

    if [[ ! -d "${config_dir}" ]]; then
        mkdir -p "${config_dir}"
    fi

    if [[ ! -f "${config_file}" ]]; then
        echo "# Ripgrep configuration file" > "${config_file}"
    fi
}

function install()
{
    local extruct_dir
    extruct_dir=$(download_latest_release 'x86_64.*linux.*tar.gz$' "BurntSushi/ripgrep")
    cp "${extruct_dir}"/rg "${HOME}"/.local/bin/
    rm -rf "${extruct_dir}"

    "${HOME}"/.local/bin/rg --generate=complete-zsh  > ~/.zfunc/_rg

    _create_config
}

function verify()
{
    if [[ -f $(which rg) ]];then
        return 0
    else
        return 1
    fi
}

function help() # Show a list of functions
{
    awk '/^function / && ! /^function _/' "$0"
}

if [ $# -eq 0 ]; then
    help
else
    "$@"
fi
