#!/usr/bin/env bash
#
DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P "$DIR" && pwd)

source ${DIR}/../../utils/package/github


function install()
{
    local extruct_dir 
    extruct_dir=$(download_latest_release '64.*linux.*tar.gz' "BurntSushi/ripgrep")
    cp "${extruct_dir}"/rg "${HOME}"/.local/bin/
    rm -rf "${extruct_dir}"
}

function verify()
{
    if [[ -f $(which rg) ]];then
        return 0
    else
        return 1
    fi
}

function help() # Show a list of functions
{
    grep "^function" $0
}

if [ $# -eq 0 ]; then
    help
else
    "$@"
fi
