alias k='kubectl'
alias kgn='kubectl get nodes'
alias kgp='kubectl get pods'
alias kgn='kubectl get nodes'
alias kgd='kubectl get deployments.apps'
alias kgr='kubectl get replicasets.apps'

alias kdp='kubectl describe pod'
alias kdelpod='kubectl delete pod'
alias kgall='kubectl get all,pv,pvc,secrets,configmaps,ingress'
