#version: "3.9"  # optional since v1.27.0
services:
  dotfile-test:
    build: .
    image: dotfile-test
    volumes:
      - ../../:/tmp/dotfiles
      - /tmp/dotfiles-test:/tmp/dotfiles-test
      - ./scripts/test_dotfiles_full_installation.sh:/usr/local/bin/test_dotfiles_full_installation.sh:ro
    working_dir: /tmp/dotfiles
    #runtime: sysbox-runc
