#!/usr/bin/env bash
DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P $DIR && pwd)

source $DIR/config

function run()
{
    echo DEBUG: docker run -it -v ${DOTFILE}:/tmp/dotfile -w /tmp/dotfile --rm ${DOCKER_IMAGE_NAME}
    docker run -it -v ${DOTFILE}:/tmp/dotfile -w /tmp/dotfile --rm ${DOCKER_IMAGE_NAME}
}

run
