#!/bin/bash
DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P "${DIR}" && pwd)

function _copy_fonts() # Link regolith folder to ~/.config/regolith3
{
    mkdir -p "${HOME}"/.fonts
    cp -v "${DIR}"/fonts/* "${HOME}"/.fonts/
}

function _install_maple_font()
{
    mkdir -p "${HOME}"/.fonts
    local tmp_dir
    tmp_dir=$(mktemp -d)
    curl -sL -o "${tmp_dir}/MapleMono-NF.zip" \
        https://github.com/subframe7536/maple-font/releases/latest/download/MapleMono-NF.zip
    unzip -oq "${tmp_dir}/MapleMono-NF.zip" -d "${tmp_dir}"
    cp -v "${tmp_dir}"/MapleMono-NF-*.ttf "${HOME}"/.fonts/
    rm -rf "${tmp_dir}"
}

function verify() # Verify the installation
{
    :
}


function install()
{
    _copy_fonts
    _install_maple_font
    fc-cache -f "${HOME}"/.fonts
}

function help # Show a list of functions
{
    awk '/^function / && ! /^function _/' "$0"
}

if [ $# -eq 0 ]; then
    help
else
    "$@"
fi
