#!/bin/bash

DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P $DIR && pwd)

source "${DIR}"/../../utils/package/apt

ZSH="$HOME/.oh-my-zsh"

# ZSH_CUSTOM the path of the user settings
export ZSH_CUSTOM="$HOME/.config/zsh"

function install_dependenices {
    sudo apt update -y
    fast_apt_install git
    fast_apt_install tree
}

function install_zsh {
    fast_apt_install zsh
}

function install_powerlevel10k() {
  git clone https://github.com/romkatv/powerlevel10k.git ~/.powerlevel10k --depth=1
}

#function plugin
#{
#
    #local plugin_path="$ZSH_CUSTOM/plugins"
    #local github_url="https://github.com/zsh-users"
    #mkdir -p "$plugin_path"
    #git clone "$github_url/zsh-syntax-highlighting" "$plugin_path/zsh-syntax-highlighting"
    #git clone "$github_url/zsh-autosuggestions" "$plugin_path/zsh-autosuggestions"
#}


function link_files
{
    echo ======= Start Link Files =======
    # export -f _smart_link

    # Link zshrc
    echo ln -sf "$DIR/zshrc" "$HOME/.zshrc"
    ln -sf "$DIR/zshrc" "$HOME/.zshrc"

    # Link configs
    ln -sf "$DIR/zsh_config" "$HOME/.config/zsh"
    echo ======= End Link Files =======
}

function set_zsh_as_default_shell() {
    zsh_bin="$(which zsh)"
    echo "Changing user's shell to $zsh_bin... "
    if [[ "$SHELL" =~ /zsh ]]; then
        echo 'already set'
    else
        chsh -s "$zsh_bin"
    fi
}

function verify_default_shell(){
    if grep -E "$USER.*zsh" /etc/passwd; then
        return 0
    else
        return 1
    fi
}

function verify_zsh_install(){
    if [[ -f $(which zsh) ]];then
        return 0
    else
        return 1
    fi
}

function verify()
{
    if verify_zsh_install; then
        echo "Zsh is installed"
    else
        echo "Zsh is not installed"
        return 1
    fi

    if verify_default_shell; then
        echo "Default shell is zsh"
    else
        echo "Default shell is not zsh"
        return 1
    fi

    return 0
}

function install
{
    install_dependenices
    install_zsh
    set_zsh_as_default_shell
    link_files
    install_powerlevel10k

}

function help # Show a list of functions
{
    awk '/^function / && ! /^function _/' "$0"
}

if [ $# -eq 0 ]; then
    help
else
    "$@"
fi
