#!/bin/bash

DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P $DIR && pwd)

source "${DIR}"/../../utils/package/apt
source "${DIR}"/../../utils/install_generic_software.sh

ZSH="$HOME/.oh-my-zsh"

# ZSH_CUSTOM the path of the user settings
export ZSH_CUSTOM="$HOME/.config/zsh"
export ZSH_CUSTOM_PLUGIN="${ZSH_CUSTOM}/plugins"

function install_dependenices {
    sudo apt update -y
    fast_apt_install git
    fast_apt_install tree
}

function install_zsh {
    fast_apt_install zsh
}

function install_powerlevel10k() {
  git clone https://github.com/romkatv/powerlevel10k.git ~/.powerlevel10k --depth=1
}

function install_starship() {
    echo "Installing Starship prompt..."
    curl -sS https://starship.rs/install.sh | sh -s -- -y
}

function plugin
{
    local github_url="https://github.com/zsh-users"
    mkdir -p "${ZSH_CUSTOM_PLUGIN}"
    git clone "${github_url}/zsh-autosuggestions" "${ZSH_CUSTOM_PLUGIN}/zsh-autosuggestions"
    git clone "${github_url}/zsh-history-substring-search" "${ZSH_CUSTOM_PLUGIN}/zsh-history-substring-search"
    git clone "${github_url}/fast-syntax-highlighting" "${ZSH_CUSTOM_PLUGIN}/fast-syntax-highlighting"
}


function link_files
{
    echo ======= Start Link Files =======
    # export -f _smart_link

    # Link zshrc
    if [ ! -L "$HOME/.zshrc" ]; then
        echo "Creating a link for .zshrc"
        echo -e "\t"ln -sf "$DIR/zshrc" "$HOME/.zshrc"
        ln -sf "$DIR/zshrc" "$HOME/.zshrc"
    fi
    # Link configs
    if [ ! -L "$HOME/.config/zsh" ]; then
        echo "Creating a link for the configuration file of zsh ~/.config/zsh"
        echo -e "\t"ln -sf "$DIR/zsh_config" "$HOME/.config/zsh"
        ln -sf "$DIR/zsh_config" "$HOME/.config/zsh"
    fi

    # Create zfunc directory for ZSH completions
    if [ ! -d "$HOME/.zfunc" ]; then
        echo "Creating ZSH completions directory ~/.zfunc"
        mkdir -p "$HOME/.zfunc"
    fi

    echo ======= End Link Files =======
}

function set_zsh_as_default_shell() {
    zsh_bin="$(which zsh)"
    echo "Changing user's shell to $zsh_bin... "
    if [[ "$SHELL" =~ /zsh ]]; then
        echo 'already set'
    else
        chsh -s "$zsh_bin"
    fi
}

function verify_default_shell(){
    if grep -E "$USER.*zsh" /etc/passwd; then
        return 0
    else
        return 1
    fi
}

function verify_zsh_install(){
    if [[ -f $(which zsh) ]];then
        return 0
    else
        return 1
    fi
}

function verify()
{
    if verify_zsh_install; then
        echo "Zsh is installed"
    else
        echo "Zsh is not installed"
        return 1
    fi

    if verify_default_shell; then
        echo "Default shell is zsh"
    else
        echo "Default shell is not zsh"
        return 1
    fi

    return 0
}

function install
{
    install_dependenices
    install_zsh
    set_zsh_as_default_shell
    link_files
    install_powerlevel10k
    install_starship
    plugin
}

function help # Show a list of functions
{
    awk '/^function / && ! /^function _/' "$0"
}

if [ $# -eq 0 ]; then
    help
else
    "$@"
fi
