#!/bin/bash

DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P $DIR && pwd)

ZSH="$HOME/.oh-my-zsh" 

# ZSH_CUSTOM the path of the user settings
export ZSH_CUSTOM="$HOME/.config/zsh" 

function install_dependenices {
    sudo apt update -y
    sudo apt-get install -y \
        git
}

function install_zsh {
    sudo apt-get install -y \
        zsh
}

function install_powerlevel10k() {
  git clone https://github.com/romkatv/powerlevel10k.git ~/.powerlevel10k --depth=1
}

#function plugin
#{
#
    #local plugin_path="$ZSH_CUSTOM/plugins"
    #local github_url="https://github.com/zsh-users"
    #mkdir -p "$plugin_path"
    #git clone "$github_url/zsh-syntax-highlighting" "$plugin_path/zsh-syntax-highlighting"
    #git clone "$github_url/zsh-autosuggestions" "$plugin_path/zsh-autosuggestions"
#}


function link_files
{
    echo ======= Start Link Files =======
    # export -f _smart_link

    # Link zshrc
    echo ln -sf "$DIR/zshrc" "$HOME/.zshrc"
    ln -sf "$DIR/zshrc" "$HOME/.zshrc"

    # Link configs
    ln -sf "$DIR/zsh_config" "$HOME/.config/zsh"
    echo ======= End Link Files =======
}

function set_zsh_as_default_shell() {
    zsh_bin="$(which zsh)"
    echo "Changing user's shell to $zsh_bin... "
    #if [[ "$SHELL" =~ /zsh ]]; then
        #echo 'already set'
    #else
        #chsh -s "$zsh_bin"
    #fi
}

function verify()
{
    if [[ -f $(which zsh) ]];then
        return 0
    else
        return 1
    fi
}

function install
{
    install_dependenices
    install_zsh
    set_zsh_as_default_shell
    link_files
    install_powerlevel10k

}

function help # Show a list of functions
{
    awk '/^function / && ! /^function _/' "$0"
}

if [ $# -eq 0 ]; then
    help
else
    "$@"
fi

