autoload -U +X bashcompinit && bashcompinit
autoload -U +X compinit && compinit

export ZSH_COMPDUMP=$ZSH/cache/.zcompdump-$HOST
# fpath=(~/.zsh/completion $fpath)
fpath=(~/.zsh/completion $fpath ~/.zfunc)
zstyle ":completion:*:descriptions" format "%B%d%b"
# If you come from bash you might have to change your $PATH.
if [ -d /usr/local/go/bin ]; then
    export PATH=$HOME/.local/go/bin:/usr/local/go/bin:$PATH
    export GOPATH=$HOME/.local/go
fi
#export PATH="$(yarn globa bin):$PATH"
# export RECORDING=${RECORDING:-"false"}
# export RECORDING="true"

# eval "$(direnv hook zsh)"
# Path to your oh-my-zsh installation.
USER=$(whoami)
if [ -d "/home/$USER/.oh-my-zsh" ]; then
    export ZSH=/home/$USER/.oh-my-zsh
fi

TRAPWINCH() {
  zle && { zle reset-prompt; zle -R }
}

VISUAL=nvim; export VISUAL EDITOR=nvim; export EDITOR


HIST_STAMPS="dd.mm.yyyy"

export ZSH_CUSTOM="$HOME/.config/zsh"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  zsh-syntax-highlighting 
  zsh-autosuggestions
  docker
)
  # z
source $ZSH/oh-my-zsh.sh

# User configuration

# You may need to manually set your language environment
export LANG=en_US.UTF-8

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

autoload -Uz compinit
zstyle ':completion:*' menu select

# export WIKI_URL="https://confluence.solaredge.com"
export PYENV_ROOT="$HOME"/.pyenv
export PATH="$PYENV_ROOT"/bin:"$PATH"



export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

fpath+=~/.zfunc
if [[ "$RECORDING" == "true" ]]; then
    export PS1=" $ "
fi
