# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

autoload -U +X bashcompinit && bashcompinit
autoload -U +X compinit && compinit

VISUAL=nvim; export VISUAL EDITOR=nvim; export EDITOR

HIST_STAMPS="dd.mm.yyyy"


export ZSH_CUSTOM="$HOME/.config/zsh"

if [ -d ${ZSH_CUSTOM} ]; then 
     for f in ${ZSH_CUSTOM}/*.zsh; do source $f; done
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.powerlevel10k/powerlevel10k.zsh-theme
