#!/usr/bin/env bash

function install_fzf() {
    echo 'Installing FZF... '
    if [ -e ~/.fzf ]; then
        echo 'already installed.'
    else
        git clone https://github.com/junegunn/fzf.git ~/.fzf --depth 1
        ~/.fzf/install --completion --key-bindings --no-update-rc
    fi
}

function install_packages() # Install additional package for neovim
{
    ## To connect the clipboard of the neovim and the linux
    echo ====== Install additional packages =====
    sudo apt-get update
    sudo apt-get install -y git fd-find
    sudo ln -s "$(command -v fdfind)" /usr/local/bin/fd
    echo ======== End ========
}

function verify()
{
    if [[ -f ~/.fzf/bin/fzf ]]; then

        return 0
    else
        return 1
    fi


}

function install
{
    install_packages
    install_fzf
}


function help # Show a list of functions
{
    awk '/^function / && ! /^function _/' "$0"
}

if [ $# -eq 0 ]; then
    help
else
    "$@"
fi
