#!/usr/bin/env bash

DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P "${DIR}" && pwd)

source "${DIR}"/../../utils/package/github

function verify() # Verify the installation
{
    :
}

function install_balena_cli(){
    download_latest_release 'balena-cli-v.*linux-x64-standalone.zip$' 'balena-io/balena-cli'
    extruct_dir=$(download_latest_release 'balena-cli-v.*linux-x64-standalone.zip$' "balena-io/balena-cli")
    echo $extruct_dir
}


function install()
{
    install_balena_cli
    :
}

function help # Show a list of functions
{
    awk '/^function / && ! /^function _/' "$0"
}

if [ $# -eq 0 ]; then
    help
else
    "$@"
fi
