# Mouse behavior for libinput pointer devices (mice, trackballs, etc.):
# - Middle-button scroll: hold middle button and move mouse to scroll.
# - Middle emulation: press left and right button at the same time = middle click.
Section "InputClass"
    Identifier "Middle button scroll and emulation"
    MatchIsPointer "on"
    Driver "libinput"
    Option "ScrollMethod" "button"
    Option "ScrollButton" "2"
    Option "MiddleEmulation" "true"
EndSection
