#!/bin/bash
DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P "${DIR}" && pwd)

function _link() # Link regolith folder to ~/.config/regolith3
{
    ln -s "${DIR}/regolith3" "${HOME}/.config/regolith3"
}

function _regolith3_install()
{


    wget -qO - https://regolith-desktop.org/regolith.key | \
    gpg --dearmor | sudo tee /usr/share/keyrings/regolith-archive-keyring.gpg > /dev/null

    echo deb "[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] \
        https://regolith-desktop.org/release-3_0-ubuntu-jammy-amd64 jammy main" | \
        sudo tee /etc/apt/sources.list.d/regolith.list

    sudo apt update

    sudo apt install -y \
        regolith-desktop \
        regolith-session-flashback \
        regolith-look-lascaille

}

function verify() # Verify the installation
{
    :
}


function install()
{
    _regolith3_install
    _link
}

function help # Show a list of functions
{
    awk '/^function / && ! /^function _/' "$0"
}

if [ $# -eq 0 ]; then
    help
else
    "$@"
fi
