#!/bin/bash
DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P "${DIR}" && pwd)

# Source generic software installation script
if [ -f "${DIR}/../../utils/install_generic_software.sh" ]; then
    source "${DIR}/../../utils/install_generic_software.sh"
    # Ensure generic software is installed before proceeding
    ensure_generic_software
fi

function _link() # Link regolith folder to ~/.config/regolith3
{
    ln -s "${DIR}/regolith3" "${HOME}/.config/regolith3"
}

function _regolith3_install()
{
    # Detect Ubuntu codename
    UBUNTU_CODENAME=$(lsb_release -cs)
    
    # Validate supported Ubuntu versions for Regolith 3.0
    case "$UBUNTU_CODENAME" in
        jammy|focal|noble)
            echo "Installing Regolith for Ubuntu $UBUNTU_CODENAME"
            ;;
        *)
            echo "Warning: Ubuntu $UBUNTU_CODENAME may not be officially supported by Regolith 3.0"
            echo "Falling back to jammy repository"
            UBUNTU_CODENAME="jammy"
            ;;
    esac

    wget -qO - https://regolith-desktop.org/regolith.key | \
    gpg --dearmor | sudo tee /usr/share/keyrings/regolith-archive-keyring.gpg > /dev/null

    echo deb "[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] \
        https://regolith-desktop.org/release-3_0-ubuntu-${UBUNTU_CODENAME}-amd64 ${UBUNTU_CODENAME} main" | \
        sudo tee /etc/apt/sources.list.d/regolith.list

    sudo apt update

    sudo apt install -y \
        regolith-desktop \
        regolith-look-lascaille

}

function _i3xrocks(){
    sudo apt-get install -y \
        i3xrocks-battery \
        i3xrocks-volume \
        i3xrocks-bluetooth \
        i3xrocks-key-indicator \
        i3xrocks-keyboard-layout \
        i3xrocks-nm-vpn
}

function verify() # Verify the installation
{
    :
}


function install()
{
    _regolith3_install
    _link
}

function help # Show a list of functions
{
    awk '/^function / && ! /^function _/' "$0"
}

if [ $# -eq 0 ]; then
    help
else
    "$@"
fi
