#!/usr/bin/env bash

set -e

DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P "${DIR}" && pwd)

source "${DIR}"/../../../utils/package/apt
#source "${DIR}"/../../utils/package/github
source "${DIR}"/../../../utils/smart_link


function _add_wezterm_repository()
{
    curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
    echo 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
    sudo chmod 644 /usr/share/keyrings/wezterm-fury.gpg
    sudo apt update

}

function _install_wezterm()
{
    fast_apt_install wezterm

}

function _set_configs(){
    mkdir -p "${HOME}/.config/wezterm"
    smart_sym_link "${DIR}/wezterm.lua" "${HOME}/.config/wezterm/wezterm.lua"
}

function verify() # Verify the installation
{
    :
}


function install()
{
    _add_wezterm_repository
    _install_wezterm
    _set_configs
}

function help # Show a list of functions
{
    awk '/^function / && ! /^function _/' "$0"
}

if [ $# -eq 0 ]; then
    help
else
    "$@"
fi
