#!/bin/bash

DIR=$(dirname "${BASH_SOURCE[0]}")
DIR=$(cd -P "$DIR" && pwd)

source "${DIR}"/../../utils/package/github

function link_files()
{
    echo ======= Link Files =======
    ln -sf "$DIR"/gitconfig "$HOME"/.gitconfig
    echo =======   End   =======
}

function install_meld()
{
    VERSION="meld-3.22.0"
    echo ======= install meld version $VERSION =======
    sudo apt-get install -y \
        intltool \
        itstool \
        gir1.2-gtksource-3.0 \
        libxml2-utils \
        libgirepository1.0-dev


    LIB_VERSION=$(echo $VERSION | sed 's/meld-\([0-9]\+.[0-9]\+\).*/\1/')
    mkdir -p "$HOME"/Downloads/apps/meld
    wget -P "$HOME"/Downloads/apps/meld https://download.gnome.org/sources/meld/"$LIB_VERSION"/${VERSION}.tar.xz
    tar -C "$HOME"/Downloads/apps/meld -xvf "$HOME"/Downloads/apps/meld/${VERSION}.tar.xz

    pushd "$HOME"/Downloads/apps/meld/${VERSION}/ || exit  # Must install from the library
    sudo ./setup.py install --prefix=/usr
    popd - || exit
    echo ======= End  =======
}

function install_cdiff()
{
    pipx install cdiff
}

function install()
{
    [ -n "${DISPLAY}" ] && install_meld
    install_cdiff
    link_files
}

"$@"
