#!/usr/bin/env bash

source ./scratchpad_tmux_common  # main function

export session_name=wiki
export WIKI_GLOBAL_PATH=${WIKI_GLOBAL_PATH:-$HOME/projects/private/wiki}

function build_session() {
    tmux new-session -d -s "${session_name}" -n WikiPri
    tmux send-keys -t "${session_name}" "nvim +ObsidianSwitchPrivate" C-m

    tmux new-window -t "${session_name}" -c "${WIKI_GLOBAL_PATH}" -n WikiWork
    tmux send-keys -t "${session_name}" "nvim +ObsidianSwitchWork" C-m

    tmux select-window -t "${session_name}":WikiPri
}

main  # From file scratchpad_tmux_common
