#!/usr/bin/env bash
function __verify_docker_permissions()
{
    # NOTE: utile function, not for the verification stage
    # If the permissions is correct I can remove the `sudo` from the verify commands
    # return 1 if the permission is only for sudo
    # return 0 if the permission are for the users
    :
}

function _install_docker_engine_with_buildx()
{
    # Original tutorial: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
    echo ====== START: Install docker engine with buildx =====

    echo == Install packages ==
    sudo apt-get update
    sudo apt-get install \
        ca-certificates \
        curl \
        gnupg \
        lsb-release -y

    echo == Add Docker’s official GPG key ==
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
    echo == Set up the docker repository ==
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    echo == Install docker engine with buildx ==
    sudo apt-get update
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
    echo ====== END: Install docker engine with buildx =====
}

function _fix_docker_permissions()
{
    # Original tutorial: https://docs.docker.com/engine/install/linux-postinstall/
    echo ====== START: Fix docker permissions =====
    echo == Create the docker group ==
    sudo groupadd docker

    echo == Add your user to the docker group ==
    sudo usermod -aG docker $USER

    newgrp docker  # Remove the needs of logout and login
    echo ====== END: Fix docker permissions =====
}

function _verify_fix_docker_permissions()
{
    # Run docker command without sudo
    local test-image="hello-world"
    if ! docker run "${test-image}"; then
        echo "INSTALL_FAILED: Docker permission fix WASN'T install successfully"
        return 1
    else
        docker rmi "${test-image}"
        echo "INSTALL_SUCCESS: Docker permission fix install successfully"
        return 0
    fi
}

function _verify_docker_engine()
{
    local test-image="hello-world"
    if ! sudo docker run "${test-image}"; then
        echo "INSTALL_FAILED: Docker permission fix WASN'T install successfully"
        return 1
    else
        sudo docker rmi "${test-image}"
        echo "INSTALL_SUCCESS: Docker permission fix install successfully"
        return 0
    fi
}

function _verify_buildx()
{
    echo "NOTE: WIP verify buildx installation not support yet"
    echo "Continue"
}

function install()
{
    _install_docker_engine_with_buildx
    _fix_docker_permissions
}

function verify()
{
    _verify_docker_engine
    _verify_buildx
    _verify_fix_docker_permissions
}

function help() # Show a list of functions
{
    grep "^function" $0
}

if [ $# -eq 0 ]; then
    help
else
    "$@"
fi

