start=`date +%s`
autoload -U +X bashcompinit && bashcompinit
autoload -U +X compinit && compinit

export ZSH_COMPDUMP=$ZSH/cache/.zcompdump-$HOST
# fpath=(~/.zsh/completion $fpath)
fpath=(~/.zsh/completion $fpath ~/.zfunc)
zstyle ":completion:*:descriptions" format "%B%d%b"
#
# export RECORDING=${RECORDING:-"false"}
# export RECORDING="true"
#
eval "$(direnv hook zsh)"

# Path to your oh-my-zsh installation.
USER=$(whoami)
if [ -d "/home/$USER/.oh-my-zsh" ]; then
    export ZSH=/home/$USER/.oh-my-zsh
fi

TRAPWINCH() {
  zle && { zle reset-prompt; zle -R }
}

VISUAL=nvim; export VISUAL EDITOR=nvim; export EDITOR


HIST_STAMPS="dd.mm.yyyy"

export ZSH_CUSTOM="$HOME/.config/zsh"
# Exclude some commands
ZSH_COMMAND_TIME_EXCLUDE=(vim mcedit man vi nvim tig git fg)

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  command-time
  notification-time
  git
  zsh-syntax-highlighting 
  zsh-autosuggestions
  docker
  taskwarrior
)
  # z
[ -f ${ZSH}/oh-my-zsh.sh ] && source ${ZSH}/oh-my-zsh.sh

# User configuration

# You may need to manually set your language environment
export LANG=en_US.UTF-8

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

autoload -Uz compinit
zstyle ':completion:*' menu select



fpath+=~/.zfunc
fpath+=/usr/local/share/zsh/site-functions
if [[ "$RECORDING" == "true" ]]; then
    export PS1=" $ "
fi
export DOTFILES_WORK_PATH="$HOME/.dotfiles_work"
if [ -d "${DOTFILES_WORK_PATH}/zsh" ]; then
    for f in ${DOTFILES_WORK_PATH}/zsh/*.zsh; do source $f; done
fi

if [ -e /home/yehonatan/.nix-profile/etc/profile.d/nix.sh ]; then . /home/yehonatan/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

[ -f ${HOME}/.config/broot/launcher/bash/br ] && source ${HOME}/.config/broot/launcher/bash/br
[ -f ${HOME}/.config/zsh/invoke-completion.sh ] && source ~/.config/zsh/invoke-completion.sh
eval "$(register-python-argcomplete gitlab)"

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"
#eval "$(zoxide init zsh)"
export PATH=$PATH:/usr/local/bin
export PATH="$HOME/.jenv/bin:$PATH"
time (eval "$(jenv init -)")
export NVM_DIR="$HOME/.config/nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH=/home/yehonatan/.nimble/bin:$PATH
end=`date +%s`
echo Execution time was `expr $end - $start` seconds.
