#!/bin/bash

sleep_time=1
file_path="$HOME/.time_idle"
counter=$(<$file_path)

while [ 1 ]; do
    currentTime=$(xprintidle)
    if [[ "$(( $currentTime / 1000 ))" -lt 10 ]]; then
        counter=$(($counter+$sleep_time))
        echo $counter > $file_path
    fi
    sleep $sleep_time
done
